# Adapted from https://github.com/ammaraskar/sphinx-action and https://github.com/ammaraskar/sphinx-action-test
name: "Push Docs to gh-pages"

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: python -m pip install -r docs/requirements_docs.txt
          docs-folder: "docs/"
          build-command: "sphinx-build -b html source/ build/html -w /tmp/sphinx-log"

      # Publish built docs to gh-pages branch.
      # ===============================
      - name: Commit documentation changes
        run: |
          git clone https://github.com/RedVoxInc/Skyfall.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

    # ===============================
