name: "Pull Request Docs Check"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          build-command: "sphinx-build -b html source/ build/html -w /tmp/sphinx-log"
      # Create an artifact of the html output .
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/build/html/
